[client]
showErrorDetails = true

[theme]
primaryColor = "#00D1FF"
backgroundColor = "#0f0f0f"
secondaryBackgroundColor = "#1a1a1a"
textColor = "#FFFFFF"
font = "sans serif"

[logger]
level = "info"

[server]
headless = true

[runner]
magicEnabled = true
fastReruns = true
