[client]
showErrorDetails = true

[theme]
primaryColor = "#00D1FF"
backgroundColor = "#0f0f0f"
secondaryBackgroundColor = "#1a1a1a"
textColor = "#FFFFFF"

[logger]
level = "info"

[server]
headless = true
port = 8501
enableXsrfProtection = true
enableCORS = true
